import "./globals.scss";
import { Providers } from "@/redux/provider";
import { Poppins } from "next/font/google";
import CopyProtection from "@/components/CopyProtection";

export const metadata = {
  title: "MGD App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-primary",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <link rel="icon" href="favicon.ico" sizes="any" />
      </head>

      <body className={`${poppins.variable}`}>
        {/* ✅ GLOBAL COPY PROTECTION (NO GA) */}
        <CopyProtection />

        {/* ✅ YOUR ORIGINAL PROVIDER */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
