import "./globals.scss";
import { Providers } from "@/redux/provider";
import { DM_Sans } from "next/font/google";
import CopyProtection from "@/components/CopyProtection";

export const metadata = {
  title: "MGD App",
  description: "Generated by create next app",
};

const dmSans = DM_Sans({
  weight: ["400", "500", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-primary",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <link rel="icon" href="favicon.ico" sizes="any" />
      </head>

      <body className={`${dmSans.variable}`}>
        {/* ✅ GLOBAL COPY PROTECTION (NO GA) */}
        <CopyProtection />

        {/* ✅ YOUR ORIGINAL PROVIDER */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
